fix functions

diff --git a/src/commands/setup.yml b/src/commands/setup.yml
--- a/src/commands/setup.yml
+++ b/src/commands/setup.yml
@@ -12,6 +12,84 @@ steps:
         command: |
           SLS_ORB_PROVIDER_PARAM="<< parameters.provider >>"
 
+          ###
+          # Helper functions
+          ###
+          output_Provider_Selected () {
+            echo "................................."
+            echo " $1 Selected."
+            echo "................................."
+            echo
+          }
+
+          ###
+          # Provider check functions
+          ###
+          AWS_Check () {
+            output_Provider_Selected "AWS"
+            if [[ $(command -v aws --version >/dev/null 2>&1) == 1 ]]; then
+              echo "ERROR: AWS CLI NOT INSTALLED"
+              TipMsg_Install_AWS
+              exit 1
+            fi
+            if [[ -z $AWS_ACCESS_KEY_ID || -z $AWS_SECRET_ACCESS_KEY ]]; then
+              if [[ ! -f ~/.aws/credentials ]]; then
+                echo "ERROR: CREDENTIALS NOT FOUND"
+                TipMsg_Install_AWS
+                exit 1
+              fi
+            fi
+            TipMsg_Install_AWS () {
+              echo "
+              ---
+              Tip: Install the AWS CLI and authenticate prior to running the Serverless setup command.
+              Consider using the AWS CLI orb: https://circleci.com/orbs/registry/orb/circleci/aws-cli#usage-install_aws_cli
+
+              Import the AWS CLI Orb To Your Config:
+              ---
+                orbs:
+                  aws-cli: circleci/aws-cli@x.y
+              ---
+
+              Run The AWS Setup Command Prior To The Serverless Command:
+              ---
+                steps:
+                  - aws-cli/setup
+                  - serverless/setup
+              ---
+              "
+            }
+          }
+          azure_Check () {
+            output_Provider_Selected "Azure"
+          }
+          tencent_Check () {
+            output_Provider_Selected "Tencent"
+          }
+          knative_Check () {
+            output_Provider_Selected "Knative"
+          }
+          alibaba_Check () {
+            output_Provider_Selected "Alibaba"
+          }
+          cloudflare_Check () {
+            output_Provider_Selected "Cloudflare"
+          }
+          fn_Check () {
+            output_Provider_Selected "fn"
+          }
+          kubeless_Check () {
+            output_Provider_Selected "Kubeless"
+          }
+          openwhisk_Check () {
+            output_Provider_Selected "OpenWhisk"
+          }
+          spotinist_Check () {
+            output_Provider_Selected "Spotinist"
+          }
+          ###
+          # Call provider based on parameter
+          ###
           case $SLS_ORB_PROVIDER_PARAM in
             "AWS")
               AWS_Check
@@ -46,75 +124,6 @@ steps:
             *)
               other_Check
           esac
-
-          AWS_Check() {
-            output_Provider_Selected "AWS"
-            if [[ $(command -v aws --version >/dev/null 2>&1) == 1 ]]; then
-              echo "ERROR: AWS CLI NOT INSTALLED"
-              TipMsg_Install_AWS
-              exit 1
-            fi
-            if [[ -z $AWS_ACCESS_KEY_ID || -z $AWS_SECRET_ACCESS_KEY ]]; then
-              if [[ ! -f ~/.aws/credentials ]]; then
-                echo "ERROR: CREDENTIALS NOT FOUND"
-                TipMsg_Install_AWS
-                exit 1
-              fi
-            fi
-            TipMsg_Install_AWS() {
-              echo "
-              ---
-              Tip: Install the AWS CLI and authenticate prior to running the Serverless setup command.
-              Consider using the AWS CLI orb: https://circleci.com/orbs/registry/orb/circleci/aws-cli#usage-install_aws_cli
-
-              Import the AWS CLI Orb To Your Config:
-              ---
-                orbs:
-                  aws-cli: circleci/aws-cli@x.y
-              ---
-
-              Run The AWS Setup Command Prior To The Serverless Command:
-              ---
-                steps:
-                  - aws-cli/setup
-                  - serverless/setup
-              ---
-              "
-            }
-          }
-          azure_Check() {
-            output_Provider_Selected "Azure"
-          }
-          tencent_Check() {
-            output_Provider_Selected "Tencent"
-          }
-          knative_Check() {
-            output_Provider_Selected "Knative"
-          }
-          alibaba_Check() {
-            output_Provider_Selected "Alibaba"
-          }
-          cloudflare_Check() {
-            output_Provider_Selected "Cloudflare"
-          }
-          fn_Check() {
-            output_Provider_Selected "fn"
-          }
-          kubeless_Check() {
-            output_Provider_Selected "Kubeless"
-          }
-          openwhisk_Check() {
-            output_Provider_Selected "OpenWhisk"
-          }
-          spotinist_Check() {
-            output_Provider_Selected "Spotinist"
-          }
-          output_Provider_Selected() {
-            echo "................................."
-            echo " $1 Selected."
-            echo "................................."
-            echo
-          }
     - run:
         name: Install Serverless CLI
         command: |
