linted and moved to case instead of if/else

diff --git a/src/commands/setup.yml b/src/commands/setup.yml
--- a/src/commands/setup.yml
+++ b/src/commands/setup.yml
@@ -2,69 +2,127 @@
 description: >
   Install and authenticate with the Serverless CLI.
 parameters:
-    provider:
-      type: enum
-      enum: ["", "AWS", "azure", "tencent", "google", "knative", "alibaba", "cloudflare", "fn", "kubeless", "openwhisk", "spotinist"]
-      default: ""
+  provider:
+    type: enum
+    enum: ["", "AWS", "azure", "tencent", "google", "knative", "alibaba", "cloudflare", "fn", "kubeless", "openwhisk", "spotinist"]
+    default: ""
 steps:
-  - run:
-      name: Provider Check
-      command: |
-        SLS_ORB_PROVIDER_PARAM="<< parameters.provider >>"
-        # If no provider
-        if [ -z "$SLS_ORB_PROVIDER_PARAM" ]; then
-          echo "................................."
-          echo " No Cloud Provider Selected."
-          echo "................................."
-          echo
-          echo "To run deployments you must select a provider"
-        # If AWS
-        elif [ "$SLS_ORB_PROVIDER_PARAM" == "AWS" ]; then
-          echo "................................."
-          echo "          AWS Selected.          "
-          echo "................................."
-          echo
-          function TipMsg_Install_AWS() {
-            echo "
-            ---
-            Tip: Install the AWS CLI and authenticate prior to running the Serverless setup command.
-            Consider using the AWS CLI orb: https://circleci.com/orbs/registry/orb/circleci/aws-cli#usage-install_aws_cli
+    - run:
+        name: Provider Check
+        command: |
+          SLS_ORB_PROVIDER_PARAM="<< parameters.provider >>"
 
-            Import the AWS CLI Orb To Your Config:
-            ---
-              orbs:
-                aws-cli: circleci/aws-cli@x.y
-            ---
+          case $SLS_ORB_PROVIDER_PARAM in
+            "AWS")
+              AWS_Check
+              ;;
+            "azure")
+              azure_Check
+              ;;
+            "tencent")
+              tencent_Check
+              ;;
+            "knative")
+              knative_Check
+              ;;
+            "alibaba")
+              alibaba_Check
+              ;;
+            "cloudflare")
+              cloudflare_Check
+              ;;
+            "fn")
+              fn_Check
+              ;;
+            "kubeless")
+              kubeless_Check
+              ;;
+            "openwhisk")
+              openwhisk_Check
+              ;;
+            "spotinist")
+              spotinist_Check
+              ;;
+            *)
+              other_Check
+          esac
 
-            Run The AWS Setup Command Prior To The Serverless Command:
-            ---
-              steps:
-                - aws-cli/setup
-                - serverless/setup
-            ---
-            "
-          }
-          if [[ $(command -v aws --version >/dev/null 2>&1) == 1 ]]; then
-            echo "ERROR: AWS CLI NOT INSTALLED"
-            TipMsg_Install_AWS
-            exit 1
-          fi
-          if [[ -z $AWS_ACCESS_KEY_ID || -z $AWS_SECRET_ACCESS_KEY ]]; then
-            if [[ ! -f ~/.aws/credentials ]]; then
-              echo "ERROR: CREDENTIALS NOT FOUND"
+          AWS_Check() {
+            output_Provider_Selected "AWS"
+            if [[ $(command -v aws --version >/dev/null 2>&1) == 1 ]]; then
+              echo "ERROR: AWS CLI NOT INSTALLED"
               TipMsg_Install_AWS
               exit 1
             fi
+            if [[ -z $AWS_ACCESS_KEY_ID || -z $AWS_SECRET_ACCESS_KEY ]]; then
+              if [[ ! -f ~/.aws/credentials ]]; then
+                echo "ERROR: CREDENTIALS NOT FOUND"
+                TipMsg_Install_AWS
+                exit 1
+              fi
+            fi
+            TipMsg_Install_AWS() {
+              echo "
+              ---
+              Tip: Install the AWS CLI and authenticate prior to running the Serverless setup command.
+              Consider using the AWS CLI orb: https://circleci.com/orbs/registry/orb/circleci/aws-cli#usage-install_aws_cli
+
+              Import the AWS CLI Orb To Your Config:
+              ---
+                orbs:
+                  aws-cli: circleci/aws-cli@x.y
+              ---
+
+              Run The AWS Setup Command Prior To The Serverless Command:
+              ---
+                steps:
+                  - aws-cli/setup
+                  - serverless/setup
+              ---
+              "
+            }
+          }
+          azure_Check() {
+            output_Provider_Selected "Azure"
+          }
+          tencent_Check() {
+            output_Provider_Selected "Tencent"
+          }
+          knative_Check() {
+            output_Provider_Selected "Knative"
+          }
+          alibaba_Check() {
+            output_Provider_Selected "Alibaba"
+          }
+          cloudflare_Check() {
+            output_Provider_Selected "Cloudflare"
+          }
+          fn_Check() {
+            output_Provider_Selected "fn"
+          }
+          kubeless_Check() {
+            output_Provider_Selected "Kubeless"
+          }
+          openwhisk_Check() {
+            output_Provider_Selected "OpenWhisk"
+          }
+          spotinist_Check() {
+            output_Provider_Selected "Spotinist"
+          }
+          output_Provider_Selected() {
+            echo "................................."
+            echo " $1 Selected."
+            echo "................................."
+            echo
+          }
+    - run:
+        name: Install Serverless CLI
+        command: |
+          curl -o- -L https://slss.io/install | bash
+          echo "export PATH=\"$HOME/.serverless/bin:$PATH\"" >> $BASH_ENV
+          if [ -z "$SERVERLESS_ACCESS_KEY" ]; then
+            echo "Error: The environment variable SERVERLESS_ACCESS_KEY is empty.
+              Please create your serverless dashboard access key and add it to this project as a project environment vairable
+              or via contexts.
+              https://serverless.com/framework/docs/dashboard/cicd/running-in-your-own-cicd#configure-environment-variables"
           fi
-        fi
-  - run:
-      name: Install Serverless CLI
-      command: |
-        curl -o- -L https://slss.io/install | bash
-        echo "export PATH=\"$HOME/.serverless/bin:$PATH\"" >> $BASH_ENV
-        if [ -z "$SERVERLESS_ACCESS_KEY" ]; then
-          echo "Error: The environment variable SERVERLESS_ACCESS_KEY is empty. 
-            Please create your serverless dashboard access key and add it to this project as a project environment vairable 
-            or via contexts. 
-            https://serverless.com/framework/docs/dashboard/cicd/running-in-your-own-cicd#configure-environment-variables"
-        fi
